# Site Settings
title: Eukaryotic Microbiology
baseurl: "/BIOL203"



# Build Settings
theme: minima
toc_levels: 1

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - footer.html

header_pages:
  - Syllabus.md
  - Resources.md
  - Labs.md
