# Site Settings
title: Eukaryotic Microbiology
baseurl: "/BIOL203"
author: "BIOL 203 2020"


# Build Settings
theme: minima

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - footer.html

header_pages:
  - Syllabus.md
