# Site Settings
title: Eukaryotic Microbiology
baseurl: "/BIOL203"

# Build Settings
markdown: kramdown
theme: minima
kramdown:
  auto_ids: false
  toc_levels: 1

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
